
import type { Metadata } from "next";
import { Poppins, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import {DarkModeProvider} from "@/componenets/DarkModeProvider";
import {I18nProvider} from "@/componenets/I18nProvider";
import AppChrome from "@/componenets/layout/AppChrome";
import PremiumUpsellModal from "@/componenets/PremiumUpsellModal";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased`}
      >
      <I18nProvider>
        <DarkModeProvider>
            <AppChrome>{children}</AppChrome>
            <Toaster richColors position="top-right" />
            <PremiumUpsellModal />
        </DarkModeProvider>
      </I18nProvider>
      </body>
    </html>
  );
}
