package com.deutschbridge.backend.service;

import com.deutschbridge.backend.context.RequestContext;
import com.deutschbridge.backend.exception.DataNotFoundException;
import com.deutschbridge.backend.model.dto.RedemittelAnswerRequest;
import com.deutschbridge.backend.model.dto.RedemittelAnswerResponse;
import com.deutschbridge.backend.model.dto.RedemittelExerciseDto;
import com.deutschbridge.backend.model.dto.RedemittelSessionResponse;
import com.deutschbridge.backend.model.entity.RedemittelCollectionItem;
import com.deutschbridge.backend.model.entity.RedemittelExercise;
import com.deutschbridge.backend.model.entity.RedemittelProgress;
import com.deutschbridge.backend.model.entity.WritingPhrase;
import com.deutschbridge.backend.model.enums.LearningActivityType;
import com.deutschbridge.backend.model.enums.LearningModule;
import com.deutschbridge.backend.model.enums.RedemittelExerciseType;
import com.deutschbridge.backend.model.enums.RedemittelStatus;
import com.deutschbridge.backend.repository.RedemittelCollectionRepository;
import com.deutschbridge.backend.repository.RedemittelExerciseRepository;
import com.deutschbridge.backend.repository.RedemittelProgressRepository;
import com.deutschbridge.backend.repository.WritingPhraseRepository;
import com.deutschbridge.backend.service.cache.RedemittelCacheService;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;
import java.util.*;
import java.util.function.Function;
import java.util.function.Supplier;
import java.util.stream.Collectors;

/**
 * Practice ("Üben") and review ("Wiederholen") sessions. Exercises are the ones an admin authored per
 * Redemittel plus three derived from the Redemittel itself (function quiz, cloze and word order from
 * its example sentence) - nothing is generated by AI. Review picks the tier from the learner's stage
 * and moves the schedule; practice mixes the tiers, harder as it goes, and only touches the counters.
 */
@Service
public class RedemittelPracticeService {

    static final int SESSION_SIZE = 10;
    static final int MAX_PRACTICE_IDS = 20;

    /** Target share of each exercise type in a practice session: recognition / recall / situation / production. */
    static final Map<RedemittelExerciseType, Integer> PRACTICE_MIX = new EnumMap<>(Map.of(
            RedemittelExerciseType.MEANING, 30,
            RedemittelExerciseType.FILL_BLANK, 30,
            RedemittelExerciseType.SITUATION, 20,
            RedemittelExerciseType.PRODUCTION, 20));

    private final WritingPhraseRepository phraseRepository;
    private final RedemittelProgressRepository progressRepository;
    private final RedemittelCollectionRepository collectionRepository;
    private final RedemittelExerciseRepository exerciseRepository;
    private final LearningActivityService learningActivityService;
    private final RequestContext requestContext;
    private final RedemittelCacheService cacheService;
    private final RedemittelExerciseFactory factory;
    private final Random random = new Random();

    public RedemittelPracticeService(WritingPhraseRepository phraseRepository,
                                     RedemittelProgressRepository progressRepository,
                                     RedemittelCollectionRepository collectionRepository,
                                     RedemittelExerciseRepository exerciseRepository,
                                     LearningActivityService learningActivityService,
                                     RequestContext requestContext,
                                     RedemittelCacheService cacheService) {
        this.phraseRepository = phraseRepository;
        this.progressRepository = progressRepository;
        this.collectionRepository = collectionRepository;
        this.exerciseRepository = exerciseRepository;
        this.learningActivityService = learningActivityService;
        this.requestContext = requestContext;
        this.cacheService = cacheService;
        this.factory = new RedemittelExerciseFactory(random);
    }

    // ---- sessions ----

    /** The due Redemittel, soonest-due first, each with the exercise its stage calls for. */
    public RedemittelSessionResponse reviewSession(int limit) {
        String userId = requestContext.getUserId();
        LocalDateTime now = LocalDateTime.now();
        List<RedemittelProgress> due = progressRepository.findDue(userId, now, PageRequest.of(0, Math.max(1, Math.min(limit, 50))));
        List<String> ids = due.stream().map(RedemittelProgress::getPhraseId).toList();
        Map<String, WritingPhrase> phrases = activePhrases(ids);
        Map<String, List<RedemittelExercise>> exercises = exercisesByPhrase(ids);

        List<RedemittelExerciseDto> result = new ArrayList<>();
        for (RedemittelProgress p : due) {
            WritingPhrase phrase = phrases.get(p.getPhraseId());
            if (phrase == null) continue;
            pick(RedemittelScheduler.exerciseForStage(p.getStage()), phrase, exercises.get(p.getPhraseId())).ifPresent(result::add);
        }
        return new RedemittelSessionResponse(result, progressRepository.countDue(userId, now));
    }

    /**
     * A practice session over the given Redemittel or, by default, the learned and saved ones.
     * Exercise types follow PRACTICE_MIX and run from recognition to production.
     */
    public RedemittelSessionResponse practiceSession(List<String> ids, int size) {
        String userId = requestContext.getUserId();
        int count = Math.max(1, Math.min(size, 20));

        List<String> wanted;
        Map<String, RedemittelProgress> progressById = new HashMap<>();
        if (ids == null || ids.isEmpty()) {
            progressRepository.findByUserIdOrderByLearnedAtDesc(userId, PageRequest.of(0, 50))
                    .forEach(p -> progressById.put(p.getPhraseId(), p));
            wanted = new ArrayList<>(progressById.keySet());
            collectionRepository.findByUserId(userId).stream().map(RedemittelCollectionItem::getPhraseId)
                    .filter(id -> !progressById.containsKey(id)).forEach(wanted::add);
        } else {
            wanted = ids.stream().limit(MAX_PRACTICE_IDS).toList();
            progressRepository.findByUserIdAndPhraseIdIn(userId, wanted).forEach(p -> progressById.put(p.getPhraseId(), p));
        }
        if (wanted.isEmpty()) return new RedemittelSessionResponse(List.of(), 0);

        Map<String, WritingPhrase> phrases = activePhrases(wanted);
        Map<String, List<RedemittelExercise>> exercises = exercisesByPhrase(wanted);
        // Least recently practiced first.
        List<WritingPhrase> targets = wanted.stream()
                .filter(phrases::containsKey)
                .sorted(Comparator.comparing((String id) -> progressById.get(id) == null ? null : progressById.get(id).getLastReviewedAt(),
                        Comparator.nullsFirst(Comparator.naturalOrder())))
                .map(phrases::get)
                .limit(count)
                .toList();
        if (targets.isEmpty()) return new RedemittelSessionResponse(List.of(), 0);

        List<RedemittelExerciseDto> result = new ArrayList<>();
        int next = 0;
        for (RedemittelExerciseType type : allocate(count)) {
            WritingPhrase phrase = targets.get(next++ % targets.size());
            pick(type, phrase, exercises.get(phrase.getId())).ifPresent(result::add);
        }
        return new RedemittelSessionResponse(result, result.size());
    }

    /** How many exercises of each type for a session of `count`, in order of increasing difficulty. */
    static List<RedemittelExerciseType> allocate(int count) {
        int totalWeight = PRACTICE_MIX.values().stream().mapToInt(Integer::intValue).sum();
        Map<RedemittelExerciseType, Integer> amounts = new EnumMap<>(RedemittelExerciseType.class);
        int assigned = 0;
        for (RedemittelExerciseType t : RedemittelExerciseType.values()) {
            int n = count * PRACTICE_MIX.getOrDefault(t, 0) / totalWeight;
            amounts.put(t, n);
            assigned += n;
        }
        // Hand the remainder to the types with the largest fractional share.
        List<RedemittelExerciseType> byRemainder = Arrays.stream(RedemittelExerciseType.values())
                .sorted(Comparator.comparingInt((RedemittelExerciseType t) -> -(count * PRACTICE_MIX.getOrDefault(t, 0) % totalWeight)))
                .toList();
        for (int i = 0; assigned < count; i++, assigned++) {
            RedemittelExerciseType t = byRemainder.get(i % byRemainder.size());
            amounts.merge(t, 1, Integer::sum);
        }
        List<RedemittelExerciseType> sequence = new ArrayList<>();
        for (RedemittelExerciseType t : RedemittelExerciseType.values()) {
            for (int i = 0; i < amounts.get(t); i++) sequence.add(t);
        }
        return sequence;
    }

    // ---- answers ----

    /** Grades a practice answer; only the counters change, never the review schedule. */
    @Transactional
    public RedemittelAnswerResponse practice(String phraseId, RedemittelAnswerRequest request) throws DataNotFoundException {
        return answer(phraseId, request, false);
    }

    /** Grades a review answer; if the Redemittel is due, the schedule moves on (or back to tomorrow). */
    @Transactional
    public RedemittelAnswerResponse review(String phraseId, RedemittelAnswerRequest request) throws DataNotFoundException {
        return answer(phraseId, request, true);
    }

    private RedemittelAnswerResponse answer(String phraseId, RedemittelAnswerRequest request, boolean review) throws DataNotFoundException {
        if (request == null || request.exerciseId() == null) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Exercise is required.");
        }
        String userId = requestContext.getUserId();
        WritingPhrase phrase = cacheService.getActivePhrase(phraseId)
                .orElseThrow(() -> new DataNotFoundException("Redemittel not found!"));
        Optional<RedemittelExerciseType> derivedType = RedemittelExerciseFactory.autoType(request.exerciseId());
        RedemittelExercise exercise = derivedType.isPresent() ? null : cacheService.getExercises(phraseId).stream()
                .filter(e -> e.getId().equals(request.exerciseId()))
                .findFirst()
                .orElseThrow(() -> new DataNotFoundException("Exercise not found!"));
        if (derivedType.isPresent() && !factory.canDerive(derivedType.get(), phrase)) {
            throw new DataNotFoundException("Exercise not found!");
        }
        RedemittelExerciseType type = exercise == null ? derivedType.get() : exercise.getType();
        RedemittelProgress progress = progressRepository.findByUserIdAndPhraseId(userId, phraseId).orElse(null);
        if (review && progress == null) {
            throw new DataNotFoundException("Redemittel not started yet!");
        }

        boolean production = type == RedemittelExerciseType.PRODUCTION;
        boolean correct = exercise == null ? factory.isCorrectDerived(type, phrase, request.answer()) : factory.isCorrect(exercise, request.answer());
        if (production && !correct) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Please write your own sentence.");
        }

        LocalDateTime now = LocalDateTime.now();
        Integer nextInDays = null;
        LocalDateTime nextAt = null;
        if (progress != null) {
            boolean due = progress.getNextReviewAt() != null && !progress.getNextReviewAt().isAfter(now);
            if (review && due) {
                RedemittelScheduler.review(progress, correct, now);
                nextAt = progress.getNextReviewAt();
                nextInDays = nextAt == null ? null : RedemittelScheduler.INTERVAL_DAYS[progress.getStage()];
            } else {
                if (correct) progress.setCorrectCount(progress.getCorrectCount() + 1);
                else progress.setIncorrectCount(progress.getIncorrectCount() + 1);
                progress.setLastReviewedAt(now);
            }
            progressRepository.save(progress);
        }
        learningActivityService.track(userId, LearningModule.REDEMITTEL,
                review ? LearningActivityType.REDEMITTEL_REVIEWED : LearningActivityType.REDEMITTEL_PRACTICED, phraseId);

        return new RedemittelAnswerResponse(
                correct,
                production,
                exercise == null ? factory.correctAnswerDerived(type, phrase) : factory.correctAnswer(exercise),
                production ? factory.modelAnswer(phrase) : null,
                progress == null ? RedemittelStatus.NEW : progress.getStatus(),
                nextAt,
                nextInDays);
    }

    // ---- helpers ----

    /**
     * One exercise for the wanted tier: randomly among the authored exercises and the derived ones the
     * phrase supports (function quiz always; cloze and word order need an example sentence). If the
     * tier has nothing for this phrase, the nearest tier is used.
     */
    private Optional<RedemittelExerciseDto> pick(RedemittelExerciseType wantedTier, WritingPhrase phrase, List<RedemittelExercise> authored) {
        List<RedemittelExercise> stored = authored == null ? List.of() : authored;
        List<RedemittelExerciseType> tiers = new ArrayList<>(List.of(
                RedemittelExerciseType.MEANING, RedemittelExerciseType.FILL_BLANK, RedemittelExerciseType.SITUATION, RedemittelExerciseType.PRODUCTION));
        tiers.sort(Comparator.comparingInt(t -> Math.abs(t.ordinal() - wantedTier.tier().ordinal())));
        for (RedemittelExerciseType tier : tiers) {
            List<Supplier<RedemittelExerciseDto>> options = new ArrayList<>();
            for (RedemittelExercise ex : stored) {
                if (ex.getType().tier() == tier) options.add(() -> factory.toDto(ex, phrase));
            }
            for (RedemittelExerciseType t : RedemittelExerciseType.values()) {
                if (t.isDerived() && t.tier() == tier && factory.canDerive(t, phrase)) {
                    options.add(() -> factory.derive(t, phrase, cacheService.getFunctionLabels()).orElseThrow());
                }
            }
            if (!options.isEmpty()) return Optional.of(options.get(random.nextInt(options.size())).get());
        }
        return Optional.empty();
    }

    private Map<String, List<RedemittelExercise>> exercisesByPhrase(Collection<String> phraseIds) {
        if (phraseIds.isEmpty()) return Map.of();
        Map<String, List<RedemittelExercise>> result = new HashMap<>();
        for (String id : phraseIds) {
            List<RedemittelExercise> authored = cacheService.getExercises(id);
            if (!authored.isEmpty()) result.put(id, authored);
        }
        return result;
    }

    private Map<String, WritingPhrase> activePhrases(Collection<String> ids) {
        if (ids.isEmpty()) return Map.of();
        Map<String, WritingPhrase> result = new HashMap<>();
        for (String id : ids) {
            cacheService.getActivePhrase(id).ifPresent(p -> result.put(id, p));
        }
        return result;
    }
}
